"""Make migrations

Revision ID: 6956f6f2a0a1
Revises: f58a76c299eb
Create Date: 2023-10-06 06:37:22.594944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6956f6f2a0a1'
down_revision = 'f58a76c299eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))
        batch_op.drop_column('profil_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_picture', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
